### ISSUE TITLE
Updates for julia v0.6

### ISSUE THREAD

**Issue by fredrikekre** [JuliaEditorSupport/Julia-sublime#45]
In particular:
- [x] `immutable` -> `struct`
- [x] `type` -> `mutable struct`
- [x] `where`-syntax (highlight `where` as a keyword? and the `T` after `where` should perhaps be highlighted as a type also?)
![jl](https://cloud.githubusercontent.com/assets/11698744/22920622/4f55d2da-f296-11e6-8fa9-ce056c3e6a28.png)

[Complete list of changes in Julia 0.6.](https://github.com/JuliaLang/julia/blob/master/NEWS.md)

**Comment by musm** [comment]
+1

**Comment by ViktorQvarfordt** [comment]
If you provide failing tests, as in [syntax_test_julia.jl](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/syntax_test_julia.jl), i can more easily implement the features.

How should we handle backward compatibility with 0.5, should we simply keep `immutable` but also add `struct` etc? Although, when 0.6 is released, there is no point in keeping the old syntax I think.

**Comment by fredrikekre** [comment]
`immutable` and `type` are still valid in 0.6, will be removed for the next release AFAIK. So the should probably be kept and then perhaps drop 0.5 support for the next release. I will try to push some failing tests later!

**Comment by ViktorQvarfordt** [comment]
I've fixed everything that's mentioned in this issue, and I had a look in https://github.com/JuliaLang/julia/blob/master/NEWS.md and fix the remaining syntax changes that I found. I also improved highlighting of anonymous functions; the parameter `x` in `x -> 2x` is scoped with `variable.other` (and of course `where` works as expected also for anonymous functions `((x::Array{T}) where T<:Real) -> 2x`).

Highlight for supported functions has not yet been updated for 0.6. The 0.6 alpha that I pulled failed on fetching exported functions. This should be updated when 0.6 is ready.

I leave this issue open for a while, in case I missed something, let me know!

**Comment by ViktorQvarfordt** [comment]
As you can see in the last commit, I added support for supertype comparison (`Number >: Float64`) and fixed some cases where the `where` syntax was not properly highlighted from the previous commit.

**Comment by fredrikekre** [comment]
Perfect! I will try it out and report any bugs/missing things! Thanks a lot!

**Comment by musm** [comment]
In e.g.
`foo(x::T) where {T<:Integer} = T` there are still issues with the `where` not being highlighted properly.

**Comment by ViktorQvarfordt** [comment]
Thanks! This is now fixed. I had forgotten to add the `where` keyword for function declaration on assignment form.

**Comment by musm** [comment]
![image](https://cloud.githubusercontent.com/assets/4319522/25306268/c2214d94-2757-11e7-9723-260b2a6f659a.png)

I belive this case still doesn't work?

**Comment by musm** [comment]
I just updated, but I still don't see the `where` highlighted in   `foo(x::T) where {T<:Integer} = T`

**Comment by musm** [comment]
Another failing test is e.g.
`convert(::Type{Array{T}}, x::AbstractArray{S,n}) where {T,n,S} = convert(Array{T,n}, x)`
where the argument `x` is not highlighted as well

**Comment by ViktorQvarfordt** [comment]
Indeed, sorry! The `where` syntax is very flexible (or rather the type notation is flexible), there are many cases that need to be allowed... What's missing now is the case where what comes after `where` is contained in `{}`. I will fix this. Thanks for finding this!

**Comment by musm** [comment]
Thanks a lot for doing this @ViktorQvarfordt  !

**Comment by musm** [comment]
While I am at it here is another case:
![image](https://cloud.githubusercontent.com/assets/4319522/25306909/90ffa54a-2765-11e7-81af-5a7078dabdc6.png)
note how unsafe_trunc and leading_zeros are incorrectly highlighted

**Comment by ViktorQvarfordt** [comment]
Thanks for your input!

Regarding the highlighting of base functions, this is actually the intended behavior: "Built-in" functions, i.e. functions directly available without import, are highlighted as `support.function`. So `leading_zeros` and `unsafe_trunc` are highlighted because they are available by default, they do not need to be imported.

**Comment by ViktorQvarfordt** [comment]
There we have fixes for the the last ones!

Regarding this:
![image](https://cloud.githubusercontent.com/assets/4319522/25306268/c2214d94-2757-11e7-9723-260b2a6f659a.png)
Unfortunately, there is nothing that can be done with function declaration on assignment form that span multiple lines. This has been discussed in https://github.com/JuliaEditorSupport/Julia-sublime/issues/33.

**Comment by musm** [comment]
thanks!
what about this
![image](https://cloud.githubusercontent.com/assets/4319522/25307490/e086cb34-276f-11e7-9d06-3056c41dae8a.png)

note how the $N$ is not highlihted

**Comment by ViktorQvarfordt** [comment]
I didn't know you could nest `where`, I'll have a look at this. Thanks!

**Comment by musm** [comment]
yes both
`where {T,N,W}`
and 
`where T where N where W`
are valid syntax

**Comment by ViktorQvarfordt** [comment]
Hopefully this covers all `where` cases. Let me know if there are more things missing!

**Comment by musm** [comment]
I think I found another
![image](https://cloud.githubusercontent.com/assets/4319522/25314204/8082a3a4-280d-11e7-9d4b-6546ebc87b61.png)

**Comment by musm** [comment]
Another one perhaps
![image](https://cloud.githubusercontent.com/assets/4319522/25322463/4fb1c674-2885-11e7-8145-1f65c2a22dcf.png)

**Comment by ViktorQvarfordt** [comment]
Thanks! This is now fixed. It was an issue with types containing round brackets not being parsed (as in `::promote_type(Bool,T)` or `::typeof(op)`).

**Comment by musm** [comment]
thanks I guess this issue can be closed now? If I notice any other inconsistencies I will open further issues

**Comment by fredrikekre** [comment]
> I guess this issue can be closed now

Yes, I think everything I noticed have been fixed now. Thanks a lot for the quick fixes @ViktorQvarfordt !

**Comment by musm** [comment]
yes thank you @ViktorQvarfordt  for the quick fixes
